name: Build
on: [push, pull_request]
jobs:
  conda-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          conda-remove-defaults: "true"
      - name: Build
        shell: bash -l {0}
        run: |
          conda install -y openturns numpy pytest joblib ipyparallel pathos dask asyncssh sphinx numpydoc build twine
          pip install .
          pytest -s
          make html -C doc BUILDDIR=~/.local/share/otwrapy/doc
      - name: Upload doc
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git clone --depth 1 https://${{ secrets.GH_TOKEN }}@github.com/openturns/openturns.github.io.git /tmp/io
          mkdir -p /tmp/io/otwrapy/master
          cp -r ~/.local/share/otwrapy/doc/html/* /tmp/io/otwrapy/master
          cd /tmp/io
          touch .nojekyll
          git config user.email "support@gh.com"
          git config user.name "GitHub Actions"
          git add -A .
          if test `git diff HEAD | wc -c` -eq 0; then exit 0; fi
          git commit -a -m "GitHub Actions build ${GITHUB_REPOSITORY} ${GITHUB_RUN_ID}"
          git push --quiet origin master > /dev/null 2>&1
      - name: Upload PyPI
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash -l {0}
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          python -m build
          twine upload --non-interactive dist/*.whl

  conda-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          conda-remove-defaults: "true"
      - name: Build
        run: |
          conda install -y openturns joblib ipyparallel pathos dask asyncssh numpy pytest
          pytest -s

